collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7266791
  brandStrength: 0.489278
  lightness: 0.1921642
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  rhythmicContrast: 0.8768657
typography_spectrum: 0.1501866
layout_spectrum: 0.2434701
name: Shameless Yoga
