layout_spectrum: 0.5741605
typography_spectrum: 0.1501866
color:
  saturation: 0.6944517
  lightness: 0.07733402
  brandStrength: 0.489278
  rhythmicContrast: 0.3402375
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Shameless Yoga
